Repository tildeio/router.js, pull requests merged in 2020-07, with the labels that each got.

#293 Update queryParamsTransition to not change QueryParams if transition has been aborted
  lib/router/router.ts
  tests/router_test.ts
Labels: bug

#294 Drop Node < 10.
  .travis.yml
  package.json
  yarn.lock
Labels: breaking

#295 Add GitHub Actions CI setup
  .github/workflows/ci.yml
  .travis.yml
  testem.js
Labels: internal

#296 Migrate from TSLint to ESLint
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  lib/backburner/index.d.ts
  package.json
  testem.js
  tslint.json
  yarn.lock
Labels: internal

#298 Update prettier to 2.0.5.
  ember-cli-build.js
  lib/router/route-info.ts
  lib/router/router.ts
  lib/router/transition-aborted-error.ts
  lib/router/transition-intent/named-transition-intent.ts
  lib/router/transition-state.ts
  lib/router/transition.ts
  lib/router/unrecognized-url-error.ts
  package.json
  server/index.js
  tests/async_get_handler_test.ts
  tests/query_params_test.ts
  tests/route_info_test.ts
  tests/router_test.ts
  tests/test_helpers.ts
  tests/transition-aborted-error_test.ts
  tests/transition_intent_test.ts
  tests/transition_state_test.ts
  tests/unrecognized-url-error_test.ts
  tests/utils_test.ts
  yarn.lock
Labels: internal

#299 Update remaining dependencies/devDependencies to latest.
  package.json
  yarn.lock
Labels: internal

#300 Update Babel to latest.
  ember-cli-build.js
  package.json
  yarn.lock
Labels: internal

#301 Add automated release setup.
  CHANGELOG.md
  RELEASE.md
  package.json
  yarn.lock
Labels: internal
