Repository tildeio/router.js, pull requests merged in 2021-03, with the labels that each got.

#319 Ensure query params are preserved through an intermediate loading state transition
  lib/router/transition-intent/named-transition-intent.ts
  tests/router_test.ts
Labels: bug

#320 Remove testing for multiple platforms.
  .github/workflows/ci.yml
Labels: internal

#321 introduce isIntermediate flag in transition
  lib/router/router.ts
  lib/router/transition.ts
Labels: enhancement
